Libreria Numpy

In [1]:
import numpy as np

In [2]:
# arreglo de 1 dimension 
array1dim= np.array ([1,2,3,4,5,6])
array1dim
print('arreglo:',array1dim)
print('Forma del arreglo:',array1dim.shape)
print('Tipo del arreglo:',array1dim.dtype)

arreglo: [1 2 3 4 5 6]
Forma del arreglo: (6,)
Tipo del arreglo: int64


In [10]:
#array de 2 filas y 3 columnas cambiando la forma del arreglo anterior
array2dim=array1dim.reshape((2,3))
print('arreglo de 2 dimensiones:', array2dim)
print('Forma del arreglo', array2dim.shape)
print('Tipo de arreglo:', array2dim.dtype)

arreglo de 2 dimensiones: [[1 2 3]
 [4 5 6]]
Forma del arreglo (2, 3)
Tipo de arreglo: int64


In [28]:
#crear una matriz aleatoria
matriz_aleat = ((np.random.rand(4,3)*10).round())
print(matriz_aleat)

[[6. 3. 8.]
 [1. 1. 4.]
 [8. 8. 6.]
 [7. 6. 2.]]


In [33]:
#crear una matriz con una lista de listas
arr_de_listas = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('array de listas :',arr_de_listas)

array de listas : [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
#crear un array vacio 4*3
arr_cero= np.zeros((4,3))
print(arr_cero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
#crear un arreglo con unos 2*2
arr_unos = np.ones((2,2))
print(arr_unos)


[[1. 1.]
 [1. 1.]]


In [ ]:
# agregar un dato al arreglo
arr_unos[1,1] = 8
arr_unos[0,1] = 10
arr_unos[[0,0],[0,1]]= [1,4]    #agregar datos a mas de una posicion 
arr_unos

array([[1., 4.],
       [1., 8.]])